spring.application.name=crabit-backend
crabit.documentation.enabled=true
springdoc.api-docs.enabled=${crabit.documentation.enabled}
springdoc.swagger-ui.enabled=${crabit.documentation.enabled}
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
spring.flyway.enabled=false
