package com.crabit.backend.wish;

public enum LedgerEventType {
	CARD_BALANCE_CHANGE,
	WISH_DEPOSIT,
	WISH_WITHDRAWAL,
	WISH_TRANSFER,
	WISH_COMPLETION_RETURN,
	WISH_ABANDONMENT_RETURN,
	WISH_DELETION_RETURN
}
