"""Export the portable classifier, embedded Java payload, and independent oracle.

Usage:
  python export-feed-classifier.py /path/to/controller-created/crabit-data
  python export-feed-classifier.py /path/to/controller-created/crabit-data --write
  python export-feed-classifier.py /path/to/controller-created/crabit-data --check

The default prints all generated contents as one JSON document. ``--write`` updates
the three repository-owned generated files and ``--check`` verifies them byte for
byte. Both modes resolve the backend repository from this script's location.
"""
import base64
import gzip
import hashlib
import importlib.util
import json
import pathlib
import random
import subprocess
import sys
from difflib import SequenceMatcher

PIN = "02c704d2967c6c9ec042f7b33b36172c10e2c2b4"
BACKEND_ROOT = pathlib.Path(__file__).resolve().parents[2]
ARTIFACT_PATH = BACKEND_ROOT / "api/recommendation/feed-classifier-v1.json"
JAVA_PATH = BACKEND_ROOT / "src/main/java/com/crabit/backend/recommendation/FeedClassifierV1.java"
ORACLE_PATH = BACKEND_ROOT / "src/test/resources/recommendation/feed-feature-oracle.json"
sys.dont_write_bytecode = True
if len(sys.argv) not in (2, 3) or (len(sys.argv) == 3 and sys.argv[2] not in ("--write", "--check")):
    raise SystemExit(f"usage: {pathlib.Path(sys.argv[0]).name} DATA_WORKTREE [--write|--check]")
root = pathlib.Path(sys.argv[1]).resolve()
assert subprocess.check_output(["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip() == PIN
source = root / "wish_category_classifier.py"
assert subprocess.check_output(["git", "-C", str(root), "diff", "HEAD", "--", source.name]) == b""
spec = importlib.util.spec_from_file_location("pinned_classifier", source)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
module._ensure_fitted()
artifact = {
    "schema_version": 1, "algorithm": "tfidf-char-wb-2-3-v1", "source_head": PIN,
    "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
    "categories": module._category_names,
    "vocabulary": module._vectorizer.get_feature_names_out().tolist(),
    "idf": module._vectorizer.idf_.tolist(),
    "weights": module._category_vectors.toarray().tolist(),
    "threshold": module.DEFAULT_MIN_SIMILARITY, "fallback": "기타",
}
encoded = json.dumps(artifact, ensure_ascii=False, separators=(",", ":")) + "\n"
artifact_bytes = encoded.encode()
artifact_sha256 = hashlib.sha256(artifact_bytes).hexdigest()
version = "wish-category-v1@sha256:" + artifact_sha256
words = [word for group in module.CATEGORY_KEYWORDS.values() for word in group]
titles = ["", " ", "???", "나이키 축구화", "보스 헤드폰", "포켓몬 카드", "쿠션", "\t책\n  세트", "😀🎁", "İKΣ", "책\u00a0세트", "책\u001c세트"] + words
rng = random.Random(70)
titles += [" ".join(rng.choices(words, k=rng.randrange(1, 5))) for _ in range(150)]
titles += ["".join(rng.choices("가나다라마바사아자차카타파하😀! ", k=rng.randrange(1, 40))) for _ in range(100)]
pairs = [("", ""), ("tide", "diet"), ("diet", "tide"), ("😀책", "책😀"),
         ("x" + "a" * 199, "a" * 199 + "y"), ("a" * 200, "a" * 200),
         ("a" * 100 + "b" * 100, "b" * 100 + "a" * 100)]
pairs += [(rng.choice(titles), rng.choice(titles)) for _ in range(200)]
oracle = {"classifier_version": version,
          "categories": [{"title": t, "category": module.classify_wish_category(t)} for t in titles],
          "similarities": [{"left": a, "right": b, "ratio": SequenceMatcher(None, a, b).ratio()} for a,b in pairs]}
oracle_encoded = json.dumps(oracle, ensure_ascii=False, separators=(",", ":")) + "\n"

payload = base64.b64encode(gzip.compress(artifact_bytes, compresslevel=9, mtime=0)).decode()
chunks = [payload[offset:offset + 12_000] for offset in range(0, len(payload), 12_000)]
java_chunks = ",\n".join(f'            "{chunk}"' for chunk in chunks)
java_source = f'''package com.crabit.backend.recommendation;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;
import java.util.zip.GZIPInputStream;

/** Generated by scripts/recommendation/export-feed-classifier.py. */
final class FeedClassifierV1 {{
    static final String ARTIFACT_SHA256 = "{artifact_sha256}";
    private static final String[] GZIP_BASE64 = {{
{java_chunks}
    }};

    private FeedClassifierV1() {{}}

    static byte[] bytes() {{
        String encoded = String.join("", GZIP_BASE64);
        try (var gzip = new GZIPInputStream(
                new ByteArrayInputStream(Base64.getDecoder().decode(encoded)))) {{
            return gzip.readAllBytes();
        }} catch (IOException failure) {{
            throw new IllegalStateException("Cannot unpack embedded feed classifier", failure);
        }}
    }}
}}
'''

outputs = {
    ARTIFACT_PATH: encoded,
    JAVA_PATH: java_source,
    ORACLE_PATH: oracle_encoded,
}
mode = sys.argv[2] if len(sys.argv) == 3 else None
if mode == "--write":
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
elif mode == "--check":
    mismatches = [str(path.relative_to(BACKEND_ROOT)) for path, content in outputs.items()
                  if not path.is_file() or path.read_bytes() != content.encode()]
    if mismatches:
        raise SystemExit("generated classifier files are stale: " + ", ".join(mismatches))
else:
    print(json.dumps({"artifact": encoded, "java_source": java_source, "oracle": oracle_encoded},
                     ensure_ascii=False))
