package com.crabit.backend.recap;

/** Generated by the unchanged Python presenter at data commit 4738d32e179e06c232d5dea048c143a27b534a92. */
final class RecapProtocolFixtures {
	static final String WEEKLY_REQUEST = """
{
  "schema_version": 1,
  "algorithm_version": "recap-1",
  "generation_id": "00000000-0000-4000-8000-000000000001",
  "input_digest": "sha256:91e9c6ac2acc5a1a946861fbf8baaba3b1f4371f63fc11b985b1fc470b6720ef",
  "student_id": "00000000-0000-4000-8000-000000000002",
  "card_balance_account_id": "00000000-0000-4000-8000-000000000003",
  "academy_id": "00000000-0000-4000-8000-000000000004",
  "kind": "WEEKLY",
  "period": {
    "start_date": "2026-08-24",
    "end_date_exclusive": "2026-08-31",
    "timezone": "Asia/Seoul"
  },
  "reference_date": "2026-08-30",
  "snapshot_at": "2026-09-02T00:00:00Z",
  "input": {
    "representative_wish_id": "00000000-0000-4000-8000-000000000005",
    "wishes": [
      {
        "wish_id": "00000000-0000-4000-8000-000000000005",
        "title": "자전거",
        "target_amount": 100000,
        "created_at": "2026-07-01T00:00:00Z",
        "closed_at": null,
        "deleted_at": null,
        "status": "IN_PROGRESS",
        "is_representative": true,
        "saved_amount_at_period_end": 0
      }
    ],
    "effective_transactions": [],
    "visit_metrics": {
      "received_visit_count": 0,
      "unique_received_visitor_count": 0,
      "previous_week_received_visit_count": 0,
      "monthly_outgoing_visit_count": 0
    },
    "peer_metrics": {
      "habit_active_weeks": [],
      "achievement_rates": []
    },
    "success_story_candidates": []
  }
}
""";
	static final String WEEKLY_RESPONSE = """
{
  "academy_id": "00000000-0000-4000-8000-000000000004",
  "algorithm_version": "recap-1",
  "card_balance_account_id": "00000000-0000-4000-8000-000000000003",
  "generation_id": "00000000-0000-4000-8000-000000000001",
  "input_digest": "sha256:91e9c6ac2acc5a1a946861fbf8baaba3b1f4371f63fc11b985b1fc470b6720ef",
  "internal_metrics": {
    "account_id": "00000000-0000-4000-8000-000000000003",
    "milestone_crossed": [],
    "prev_total_visits": 0
  },
  "kind": "WEEKLY",
  "period": {
    "end_date_exclusive": "2026-08-31",
    "start_date": "2026-08-24",
    "timezone": "Asia/Seoul"
  },
  "schema_version": 1,
  "student_id": "00000000-0000-4000-8000-000000000002",
  "view": {
    "page1_last_week_performance": {
      "achievement": {
        "message": "지난주는 조용히 쉬어갔어요. 이번 주에 다시 시작해볼까요?",
        "net_savings": 0,
        "new_wish_count": 0,
        "save_count": 0
      },
      "milestone": {
        "message": null,
        "rate_after": 0,
        "rate_before": 0,
        "wish_title": "자전거"
      },
      "streak": {
        "message": "이번 주 저축을 시작하면 새로운 스트릭이 시작돼요!",
        "streak_weeks": 0
      }
    },
    "page2_growth_report": {
      "growth_pct": null,
      "message_growth": null,
      "message_visits": "지난주 프로필 방문은 없었어요.",
      "total_visits": 0,
      "unique_visitors": 0
    },
    "page3_academy_success_stories": {
      "message_summary": "지난주엔 아직 완주한 학원 친구가 없어요. 이번 주 첫 주인공이 되어볼까요?",
      "stories": []
    },
    "period": {
      "week_end": "2026-08-30",
      "week_start": "2026-08-24"
    }
  }
}
""";
	static final String MONTHLY_REQUEST = """
{
  "schema_version": 1,
  "algorithm_version": "recap-1",
  "generation_id": "00000000-0000-4000-8000-000000000001",
  "input_digest": "sha256:246cd3f7228b22eed21382e2d9b46bdb4f1d8246b5a82302ea4853e630f527e1",
  "student_id": "00000000-0000-4000-8000-000000000002",
  "card_balance_account_id": "00000000-0000-4000-8000-000000000003",
  "academy_id": "00000000-0000-4000-8000-000000000004",
  "kind": "MONTHLY",
  "period": {
    "start_date": "2026-08-01",
    "end_date_exclusive": "2026-09-01",
    "timezone": "Asia/Seoul"
  },
  "reference_date": "2026-08-31",
  "snapshot_at": "2026-09-02T00:00:00Z",
  "input": {
    "representative_wish_id": "00000000-0000-4000-8000-000000000005",
    "wishes": [
      {
        "wish_id": "00000000-0000-4000-8000-000000000005",
        "title": "자전거",
        "target_amount": 100000,
        "created_at": "2026-07-01T00:00:00Z",
        "closed_at": null,
        "deleted_at": null,
        "status": "IN_PROGRESS",
        "is_representative": true,
        "saved_amount_at_period_end": 150000
      }
    ],
    "effective_transactions": [
      {
        "root_event_id": "00000000-0000-4000-8000-000000000010",
        "wish_id": "00000000-0000-4000-8000-000000000005",
        "occurred_at": "2026-08-02T03:00:00Z",
        "amount": 50000,
        "type": "DEPOSIT"
      },
      {
        "root_event_id": "00000000-0000-4000-8000-000000000011",
        "wish_id": "00000000-0000-4000-8000-000000000005",
        "occurred_at": "2026-08-12T03:00:00Z",
        "amount": 50000,
        "type": "DEPOSIT"
      },
      {
        "root_event_id": "00000000-0000-4000-8000-000000000012",
        "wish_id": "00000000-0000-4000-8000-000000000005",
        "occurred_at": "2026-08-22T03:00:00Z",
        "amount": 50000,
        "type": "DEPOSIT"
      }
    ],
    "visit_metrics": {
      "received_visit_count": 0,
      "unique_received_visitor_count": 0,
      "previous_week_received_visit_count": 0,
      "monthly_outgoing_visit_count": 0
    },
    "peer_metrics": {
      "habit_active_weeks": [],
      "achievement_rates": []
    },
    "success_story_candidates": []
  }
}
""";
	static final String MONTHLY_RESPONSE = """
{
  "academy_id": "00000000-0000-4000-8000-000000000004",
  "algorithm_version": "recap-1",
  "card_balance_account_id": "00000000-0000-4000-8000-000000000003",
  "generation_id": "00000000-0000-4000-8000-000000000001",
  "input_digest": "sha256:246cd3f7228b22eed21382e2d9b46bdb4f1d8246b5a82302ea4853e630f527e1",
  "internal_metrics": {
    "account_id": "00000000-0000-4000-8000-000000000003",
    "classification_debug": {
      "is_fallback": true,
      "priority_matched": 4
    },
    "core_metrics": {
      "abandon_count": 0,
      "avg_amount": 50000,
      "pace_bias": -0.3333333333333333,
      "regularity_std": 0,
      "save_count": 3,
      "transfer_count": 0,
      "visit_count": 0
    }
  },
  "kind": "MONTHLY",
  "period": {
    "end_date_exclusive": "2026-09-01",
    "start_date": "2026-08-01",
    "timezone": "Asia/Seoul"
  },
  "schema_version": 1,
  "student_id": "00000000-0000-4000-8000-000000000002",
  "view": {
    "group_comparison": {
      "achievement_percentile": null,
      "achievement_percentile_status": "no_peers",
      "habit_percentile": null,
      "habit_percentile_status": "no_peers",
      "message_achievement": "아직 비교할 수 있는 학원 친구가 없어요.",
      "message_habit": "아직 비교할 수 있는 학원 친구가 없어요."
    },
    "is_active": true,
    "objective_performance": {
      "completed_wish_count": 0,
      "curr_rate_pct": 150,
      "message_completed_count": "이번 달엔 아직 완주한 위시가 없어요. 다음 달엔 함께 달성해봐요!",
      "message_rate_change": "자전거 목표가 0% → 150%로 +150%p 변화했어요.",
      "message_total_savings": "이번 달 총 150,000원을 모았어요.",
      "prev_rate_pct": 0,
      "representative_wish_title": "자전거",
      "total_savings": 150000
    },
    "pace_prediction": {
      "daily_pace": 4838.709677419355,
      "expected_completion_date": "2026-08-31",
      "message_daily_pace": "하루 평균 4,839원씩 모으는 속도예요.",
      "message_expected_date": "'자전거' 목표는 이미 달성했어요!",
      "message_required_daily": null,
      "required_daily_amount": null
    },
    "pattern_analysis": {
      "message_avg_amount": "한 번에 평균 50,000원씩 나누어 담았어요.",
      "message_regularity": "평균 10.0일 주기로 아주 일정하게 저축했어요.",
      "message_week_weekday": "가장 열심히 모은 주는 8월 1주차였고, 주로 수요일에 저축했어요.",
      "top_week": 1,
      "top_weekday": "수요일"
    },
    "period": {
      "month": 8,
      "year": 2026
    },
    "type_section": {
      "message": "이번 달은 나만의 속도로 위시를 살펴봤어요.",
      "type_title": "탐색형 토끼"
    }
  }
}
""";
}
